SDWIRE3_VID = 0x0BDA
SDWIRE3_PID = 0x0316
SDWIREC_VID = 0x04E8
SDWIREC_PID = 0x6001
SDWIREC_PRODUCT_STRING = "sd-wire"

USB_MASS_STORAGE_CLASS_ID = 8

PRINT_SERIAL_SECTION_WIDTH = 30
PRINT_PRODUCT_INFO_SECTION_WIDTH = 20
PRINT_BLOCK_DEV_SECTION_WIDTH = 50
